# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d319c89304b7de8782b2ce843c634efdb8f15e2c1a4870fb47ecfb779ea8486096c19448fa4d094742cb0933d2830ce065401b98e1eb1958d020f42868f89d

test:
  secret_key_base: 231d0b3bd1fbe81f98f140bfcf0b7b5f6cfe6770b2a0a44a8f5e27853bd5cc09a4dd4b4cb1d906f75434fb4d30ddc24ed10c3bb9c7532c7543328a9e0681f456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
